// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGraniteInstallation() {
  return window['go']['main']['App']['CheckGraniteInstallation']();
}

export function CheckLocalOllamaInstallation() {
  return window['go']['main']['App']['CheckLocalOllamaInstallation']();
}

export function CloseMarkdownAgentWebSocket() {
  return window['go']['main']['App']['CloseMarkdownAgentWebSocket']();
}

export function CloseWebSocketFrontend() {
  return window['go']['main']['App']['CloseWebSocketFrontend']();
}

export function CreateAIChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAIChatMessage'](arg1, arg2, arg3);
}

export function CreateKnowledgeBaseItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateKnowledgeBaseItem'](arg1, arg2, arg3, arg4);
}

export function CreateMeetingNotes(arg1, arg2) {
  return window['go']['main']['App']['CreateMeetingNotes'](arg1, arg2);
}

export function CreateTranscriptionMessage(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateTranscriptionMessage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DeleteAIChatMessage(arg1) {
  return window['go']['main']['App']['DeleteAIChatMessage'](arg1);
}

export function DeleteKnowledgeBaseItem(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeBaseItem'](arg1);
}

export function DeleteMeetingNotes(arg1) {
  return window['go']['main']['App']['DeleteMeetingNotes'](arg1);
}

export function DeleteMeetingNotesByWorkspace(arg1) {
  return window['go']['main']['App']['DeleteMeetingNotesByWorkspace'](arg1);
}

export function DeleteTranscriptionMessage(arg1) {
  return window['go']['main']['App']['DeleteTranscriptionMessage'](arg1);
}

export function DeleteTranscriptionMessagesByWorkspace(arg1) {
  return window['go']['main']['App']['DeleteTranscriptionMessagesByWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DisconnectWebSocket() {
  return window['go']['main']['App']['DisconnectWebSocket']();
}

export function DownloadGraniteModel() {
  return window['go']['main']['App']['DownloadGraniteModel']();
}

export function GetAIChatMessageByID(arg1) {
  return window['go']['main']['App']['GetAIChatMessageByID'](arg1);
}

export function GetAIChatMessagesByWorkspace(arg1) {
  return window['go']['main']['App']['GetAIChatMessagesByWorkspace'](arg1);
}

export function GetAllAIChatMessages() {
  return window['go']['main']['App']['GetAllAIChatMessages']();
}

export function GetAllKnowledgeBaseItems() {
  return window['go']['main']['App']['GetAllKnowledgeBaseItems']();
}

export function GetAllWorkspaces() {
  return window['go']['main']['App']['GetAllWorkspaces']();
}

export function GetKnowledgeBaseItemByID(arg1) {
  return window['go']['main']['App']['GetKnowledgeBaseItemByID'](arg1);
}

export function GetKnowledgeBaseItemByUniqueFileName(arg1) {
  return window['go']['main']['App']['GetKnowledgeBaseItemByUniqueFileName'](arg1);
}

export function GetKnowledgeBaseItemsByType(arg1) {
  return window['go']['main']['App']['GetKnowledgeBaseItemsByType'](arg1);
}

export function GetMeetingNotesByID(arg1) {
  return window['go']['main']['App']['GetMeetingNotesByID'](arg1);
}

export function GetMeetingNotesByWorkspace(arg1) {
  return window['go']['main']['App']['GetMeetingNotesByWorkspace'](arg1);
}

export function GetTranscriptionMessageByID(arg1) {
  return window['go']['main']['App']['GetTranscriptionMessageByID'](arg1);
}

export function GetTranscriptionMessageByMessageID(arg1) {
  return window['go']['main']['App']['GetTranscriptionMessageByMessageID'](arg1);
}

export function GetTranscriptionMessagesByDateRange(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTranscriptionMessagesByDateRange'](arg1, arg2, arg3);
}

export function GetTranscriptionMessagesByWorkspace(arg1) {
  return window['go']['main']['App']['GetTranscriptionMessagesByWorkspace'](arg1);
}

export function GetTranscriptionServerStatus() {
  return window['go']['main']['App']['GetTranscriptionServerStatus']();
}

export function GetWorkspaceByID(arg1) {
  return window['go']['main']['App']['GetWorkspaceByID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HealthCheckForFrontend() {
  return window['go']['main']['App']['HealthCheckForFrontend']();
}

export function InitializeMarkdownAgentWebSocket() {
  return window['go']['main']['App']['InitializeMarkdownAgentWebSocket']();
}

export function InitializeTranscriptionServer() {
  return window['go']['main']['App']['InitializeTranscriptionServer']();
}

export function InitializeWebSocket() {
  return window['go']['main']['App']['InitializeWebSocket']();
}

export function InitializeWebSocketFrontend() {
  return window['go']['main']['App']['InitializeWebSocketFrontend']();
}

export function IsMarkdownAgentWebSocketConnected() {
  return window['go']['main']['App']['IsMarkdownAgentWebSocketConnected']();
}

export function IsOllamaRunning() {
  return window['go']['main']['App']['IsOllamaRunning']();
}

export function MoveFilesToYumesession(arg1) {
  return window['go']['main']['App']['MoveFilesToYumesession'](arg1);
}

export function OpenAndGetPDFData(arg1) {
  return window['go']['main']['App']['OpenAndGetPDFData'](arg1);
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function RestartTranscriptionServer() {
  return window['go']['main']['App']['RestartTranscriptionServer']();
}

export function SearchKnowledgeBaseItems(arg1) {
  return window['go']['main']['App']['SearchKnowledgeBaseItems'](arg1);
}

export function SearchMeetingNotes(arg1, arg2) {
  return window['go']['main']['App']['SearchMeetingNotes'](arg1, arg2);
}

export function SendChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2, arg3);
}

export function SendChatWithSystemPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatWithSystemPrompt'](arg1, arg2, arg3);
}

export function SendMarkdownAgentMessage(arg1) {
  return window['go']['main']['App']['SendMarkdownAgentMessage'](arg1);
}

export function SendMeetingNotesRequest(arg1, arg2) {
  return window['go']['main']['App']['SendMeetingNotesRequest'](arg1, arg2);
}

export function SendSimpleChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendSimpleChatMessage'](arg1, arg2);
}

export function SendTestTranscription(arg1, arg2) {
  return window['go']['main']['App']['SendTestTranscription'](arg1, arg2);
}

export function StartOllamaServer() {
  return window['go']['main']['App']['StartOllamaServer']();
}

export function StopTranscriptionServer() {
  return window['go']['main']['App']['StopTranscriptionServer']();
}

export function SummarizeDocumentForFrontend(arg1) {
  return window['go']['main']['App']['SummarizeDocumentForFrontend'](arg1);
}

export function UpdateAIChatMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateAIChatMessage'](arg1, arg2, arg3, arg4);
}

export function UpdateKnowledgeBaseItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateKnowledgeBaseItem'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateMeetingNotes(arg1, arg2) {
  return window['go']['main']['App']['UpdateMeetingNotes'](arg1, arg2);
}

export function UpdateTranscriptionMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTranscriptionMessage'](arg1, arg2, arg3, arg4);
}

export function UpdateWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1, arg2, arg3);
}

export function UpdateWorkspaceLastOpen(arg1) {
  return window['go']['main']['App']['UpdateWorkspaceLastOpen'](arg1);
}
