// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGraniteInstallation() {
  return window['go']['main']['App']['CheckGraniteInstallation']();
}

export function CheckLocalOllamaInstallation() {
  return window['go']['main']['App']['CheckLocalOllamaInstallation']();
}

export function CreateTranscriptionMessage(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateTranscriptionMessage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DeleteTranscriptionMessage(arg1) {
  return window['go']['main']['App']['DeleteTranscriptionMessage'](arg1);
}

export function DeleteTranscriptionMessagesByWorkspace(arg1) {
  return window['go']['main']['App']['DeleteTranscriptionMessagesByWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DownloadGraniteModel() {
  return window['go']['main']['App']['DownloadGraniteModel']();
}

export function GetAllWorkspaces() {
  return window['go']['main']['App']['GetAllWorkspaces']();
}

export function GetTranscriptionMessageByID(arg1) {
  return window['go']['main']['App']['GetTranscriptionMessageByID'](arg1);
}

export function GetTranscriptionMessageByMessageID(arg1) {
  return window['go']['main']['App']['GetTranscriptionMessageByMessageID'](arg1);
}

export function GetTranscriptionMessagesByDateRange(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTranscriptionMessagesByDateRange'](arg1, arg2, arg3);
}

export function GetTranscriptionMessagesByWorkspace(arg1) {
  return window['go']['main']['App']['GetTranscriptionMessagesByWorkspace'](arg1);
}

export function GetTranscriptionServerStatus() {
  return window['go']['main']['App']['GetTranscriptionServerStatus']();
}

export function GetWorkspaceByID(arg1) {
  return window['go']['main']['App']['GetWorkspaceByID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitializeTranscriptionServer() {
  return window['go']['main']['App']['InitializeTranscriptionServer']();
}

export function InitializeWebSocket() {
  return window['go']['main']['App']['InitializeWebSocket']();
}

export function IsOllamaRunning() {
  return window['go']['main']['App']['IsOllamaRunning']();
}

export function MoveFilesToYumesession(arg1) {
  return window['go']['main']['App']['MoveFilesToYumesession'](arg1);
}

export function OpenAndGetPDFData(arg1) {
  return window['go']['main']['App']['OpenAndGetPDFData'](arg1);
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function RestartTranscriptionServer() {
  return window['go']['main']['App']['RestartTranscriptionServer']();
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SendChatWithSystemPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendChatWithSystemPrompt'](arg1, arg2);
}

export function SendSimpleChatMessage(arg1) {
  return window['go']['main']['App']['SendSimpleChatMessage'](arg1);
}

export function SendTestTranscription(arg1, arg2) {
  return window['go']['main']['App']['SendTestTranscription'](arg1, arg2);
}

export function StartOllamaServer() {
  return window['go']['main']['App']['StartOllamaServer']();
}

export function StopTranscriptionServer() {
  return window['go']['main']['App']['StopTranscriptionServer']();
}

export function UpdateTranscriptionMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTranscriptionMessage'](arg1, arg2, arg3, arg4);
}

export function UpdateWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1, arg2, arg3);
}

export function UpdateWorkspaceLastOpen(arg1) {
  return window['go']['main']['App']['UpdateWorkspaceLastOpen'](arg1);
}
