// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckGraniteInstallation():Promise<boolean>;

export function CheckLocalOllamaInstallation():Promise<boolean>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<main.Workspace>;

export function DeleteWorkspace(arg1:number):Promise<void>;

export function DownloadGraniteModel():Promise<void>;

export function GetAllWorkspaces():Promise<Array<main.Workspace>>;

export function GetTranscriptionServerStatus():Promise<Record<string, any>>;

export function GetWorkspaceByID(arg1:number):Promise<main.Workspace>;

export function Greet(arg1:string):Promise<string>;

export function InitializeTranscriptionServer():Promise<void>;

export function InitializeWebSocket():Promise<void>;

export function IsOllamaRunning():Promise<boolean>;

export function SendChatMessage(arg1:string,arg2:string):Promise<void>;

export function SendChatWithSystemPrompt(arg1:string,arg2:string):Promise<void>;

export function SendSimpleChatMessage(arg1:string):Promise<void>;

export function SendTestTranscription(arg1:string,arg2:string):Promise<void>;

export function StartOllamaServer():Promise<void>;

export function UpdateWorkspace(arg1:number,arg2:string,arg3:string):Promise<main.Workspace>;

export function UpdateWorkspaceLastOpen(arg1:number):Promise<void>;
