// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {main} from '../models';

export function CheckGraniteInstallation():Promise<boolean>;

export function CheckLocalOllamaInstallation():Promise<boolean>;

export function CreateTranscriptionMessage(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:time.Time):Promise<main.TranscriptionRecord>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<main.Workspace>;

export function DeleteTranscriptionMessage(arg1:number):Promise<void>;

export function DeleteTranscriptionMessagesByWorkspace(arg1:number):Promise<void>;

export function DeleteWorkspace(arg1:number):Promise<void>;

export function DownloadGraniteModel():Promise<void>;

export function GetAllWorkspaces():Promise<Array<main.Workspace>>;

export function GetTranscriptionMessageByID(arg1:number):Promise<main.TranscriptionRecord>;

export function GetTranscriptionMessageByMessageID(arg1:string):Promise<main.TranscriptionRecord>;

export function GetTranscriptionMessagesByDateRange(arg1:number,arg2:time.Time,arg3:time.Time):Promise<Array<main.TranscriptionRecord>>;

export function GetTranscriptionMessagesByWorkspace(arg1:number):Promise<Array<main.TranscriptionRecord>>;

export function GetTranscriptionServerStatus():Promise<Record<string, any>>;

export function GetWorkspaceByID(arg1:number):Promise<main.Workspace>;

export function Greet(arg1:string):Promise<string>;

export function InitializeTranscriptionServer():Promise<void>;

export function InitializeWebSocket():Promise<void>;

export function IsOllamaRunning():Promise<boolean>;

export function RestartTranscriptionServer():Promise<void>;

export function SendChatMessage(arg1:string,arg2:string):Promise<void>;

export function SendChatWithSystemPrompt(arg1:string,arg2:string):Promise<void>;

export function SendSimpleChatMessage(arg1:string):Promise<void>;

export function SendTestTranscription(arg1:string,arg2:string):Promise<void>;

export function StartOllamaServer():Promise<void>;

export function StopTranscriptionServer():Promise<void>;

export function UpdateTranscriptionMessage(arg1:string,arg2:string,arg3:string,arg4:time.Time):Promise<main.TranscriptionRecord>;

export function UpdateWorkspace(arg1:number,arg2:string,arg3:string):Promise<main.Workspace>;

export function UpdateWorkspaceLastOpen(arg1:number):Promise<void>;
